spring.application.name=springAIOneWayChatBot

## 1. Your Groq API Key (Keep this)
#spring.ai.openai.api-key=${OPEN_API_KEY}
#
## 2. IMPORTANT: Change the Base URL to point to Groq, not OpenAI
#spring.ai.openai.chat.options.model=${API_MODEL}

spring.profiles.active=dev


# 3. Use a model that exists on Groq (OpenAI models like gpt-4 won't work here)

spring.ai.openai.base-url=${OPEN_API_URL}
